// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAE_lHcOy-wYF1AY3zWw2tDXGhRWpNyLI',
    appId: '1:192605118895:web:e6a7bd064ba6373f104f5a',
    messagingSenderId: '192605118895',
    projectId: 'smartnews-cb9df',
    authDomain: 'smartnews-cb9df.firebaseapp.com',
    storageBucket: 'smartnews-cb9df.firebasestorage.app',
    measurementId: 'G-Q9J2QQ05ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFH87Vn0PqW_-pyzXKaUU2b2NvbMURDE',
    appId: '1:192605118895:android:41564e24ce548839104f5a',
    messagingSenderId: '192605118895',
    projectId: 'smartnews-cb9df',
    storageBucket: 'smartnews-cb9df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKHvZu8wqmnh_E6_2bwNLY8LcuAPOzJGk',
    appId: '1:192605118895:ios:d287927d1db9d99c104f5a',
    messagingSenderId: '192605118895',
    projectId: 'smartnews-cb9df',
    storageBucket: 'smartnews-cb9df.firebasestorage.app',
    iosBundleId: 'com.example.smartNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKHvZu8wqmnh_E6_2bwNLY8LcuAPOzJGk',
    appId: '1:192605118895:ios:d287927d1db9d99c104f5a',
    messagingSenderId: '192605118895',
    projectId: 'smartnews-cb9df',
    storageBucket: 'smartnews-cb9df.firebasestorage.app',
    iosBundleId: 'com.example.smartNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAE_lHcOy-wYF1AY3zWw2tDXGhRWpNyLI',
    appId: '1:192605118895:web:d8111ce5974dde61104f5a',
    messagingSenderId: '192605118895',
    projectId: 'smartnews-cb9df',
    authDomain: 'smartnews-cb9df.firebaseapp.com',
    storageBucket: 'smartnews-cb9df.firebasestorage.app',
    measurementId: 'G-XXY4MH408M',
  );
}
